import '../styles/shared/global.css'
import QueryProvider from './lib/Providers'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
            {children}
        </QueryProvider>
      </body>
    </html>
  )
}
